import { useState, useEffect } from "react";
import axios from "axios";
import Head from "next/head";
import Image from "next/image";

import Header from "../components/Header";
import Footer from "../components/Footer";
import styles from "../styles/Servicos.module.css";

export default function Servicos() {
	const [categories, setCategories] = useState([]);
	const [paths, setPaths] = useState([]);
	const [selected, setSelected] = useState(1);

	const myLoader = ({ src }) => {
		return `https://templaka.com.br/data/${src}`;
	};

	async function getCategories() {
		await axios
			.get("http://templaka.com.br/api/categories.php")
			.then((response) => {
				console.log(response.data);
				setCategories(response.data);
			})
			.catch((e) => {
				console.log(e);
			});
	}

	async function getPaths(id = 1) {
		await axios
			.get(`http://templaka.com.br/api/paths.php?id=${id}`)
			.then((response) => {
				console.log(response.data);
				setPaths(response.data);
			})
			.catch((e) => {
				console.log(e);
			});
	}
	function handleChange(id) {
		setSelected(id);
    console.log(id);
    console.log(selected);
	}

	useEffect(() => {
		getCategories();
	}, []);

	useEffect(() => {
		getPaths(selected);
	}, [selected]);

	return (
		<div className={styles.container} id="container">
			<Head>
				<title>Templaka</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className={styles.main} id="main">
				<div className={styles.titleHolder}>
					<p className={styles.title}>NOSSOS SERVIÇOS</p>
				</div>
				<div className={styles.catWrapper}>
					{categories.map((value) => (
						<div
							key={value.Id}
							className={styles.category}
							onClick={() => {
								handleChange(value.Id);
							}}
						>
							<p key={value.Id}> {value.Category} </p>
						</div>
					))}
				</div>

				<div className={styles.imgWrapper}>
					{paths.map((value) => {
						return (
							<Image
								loader={myLoader}
								src={value.Path}
								width={120}
								height={120}
								key={value.Id}
							/>
						);
					})}
				</div>
			</main>

			<Footer />
		</div>
	);
}
